### ISSUE TITLE
[Question] Customization of the scanner behavior

### ISSUE THREAD

**Issue by dmalukov** [G00fY2/quickie#10]
Hello there! 

The lib works like a charm, the only difficulty we faced is that it's impossible to customize behavior of the scanner.

For instance, we'd like to implement additional check of QR code right in the QRScannerActivity 
to avoid finishing the activity while the scanning result does not meet certain criteria.

Obviously, forking the project is an option, but maybe you can recommend something else?

**Comment by G00fY2** [comment]
Hi @dmalukov 
I see your point and I thought about this behaviour too. But from my investigation thats basically how 90% of the barcode scanner apps handle image processing. The whole camera image gets analyzed and the overlay only gives visual guidance.

**Comment by G00fY2** [comment]
Hi @dmalukov 
sorry I misunderstood your question in my previous comment.

You basically like to have an option to validate the content of a result right inside the scanner activity, right? I know that it's not ideal to check the result after the scanner activity finished.

I am not really sure what the best option would be, since we can't reference or pass in logic when launching the library Activity.

I thought about offering a regex validator. Do you think this would be sufficient?

**Comment by dmalukov** [comment]
@G00fY2 
Unfortunately no, for we have to make validation via network request.

**Comment by G00fY2** [comment]
@dmalukov 
Hm, then I see no way to achieve this with the activity based approach.
My goal is to someday create a fragment based implementation. So you could include the scanner inside your own activity.

**Comment by dmalukov** [comment]
Using a fragment might solve our problem indeed. 
Anyway, thanks for your help.

**Comment by G00fY2** [comment]
I will close this issue and create a separate feature-request ticket for a fragment based implementation.

If you heavily rely on the QR scanning feature it's maybe worth to build the CameraX and ML Kit integration by yourself. This library should be an easy starting point. Anyway thanks for your input!
