### ISSUE TITLE
Minimum SDK version - 31

### ISSUE THREAD

**Issue by MrChriZ** [G00fY2/quickie#22]
When I pull quickie into my project I get the following error:
_The minCompileSdk (31) specified in a
dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-28)._

The intro page indicates a minimum SDK of 21+
This looks to be due to the CameraView component.

I'm going to look to move to 31 - but I thought I'd mention it here.

Many thanks for your work so far.

**Comment by G00fY2** [comment]
Hi, thanks for reaching out. My readme is actually right. The **minSDK** version is 21, so devices back to Android 5.0 can run this library.

The issue that you are facing is because you don't use the latest **compileSDK** version in your project. This unfortunately prevents you from using all the latest AndroidX libraries like appcompat 1.4, lifecylce 2.4 and which this library depends on. There is nothing I could do (except downgrading dependencies which doesn't makes sense).

You should consider updating you **compileSDK** version or stick to an older version of this library for a little longer. :slightly_smiling_face:

**Comment by MrChriZ** [comment]
OK that makes sense - thanks.
