### ISSUE TITLE
[Feature Request] Scan from file

### ISSUE THREAD

**Issue by Doomsdayrs** [G00fY2/quickie#32]
Sometimes the QR code is not in person, but on the device itself.

It would be nice to have a config option to scann a file

**Comment by G00fY2** [comment]
Hi @Doomsdayrs, thanks for reaching out. Currently the focus of the library is the camera integration. But I will see if I can add some way to scan files in the future.

**Comment by getsurfboard** [comment]
We can use `InputImage.fromFilePath()` to create an InputImage process it by using BarcodeScanner.

**Comment by apelican** [comment]
So, in QRCodeAnalyzer.kt there is a call to pass the captured image to the analysis engine:
`barcodeScanner.process(imageProxy.toInputImage())` 

One might need to pass an image to a similar MLKit call in your own workflow (wherever the on-device image is sourced...)

I get a healthy part of the value of quickie is the proper MLKit configuration, so one could also explore reusing or exposing the ImageAnalysis of the library for a way to make this call yourself in your own code?

Alternatively, if you forked, one could create or extend a way to attach an image to an analyzer so it could be passed into the quickie image analysis object in QRScannerActivity.kt

**Comment by fzyzcjy** [comment]
hi, is there any updates?

**Comment by 2dust** [comment]
hi, is there any updates?

**Comment by G00fY2** [comment]
Hi and sorry for not giving any updates about this feature request.🙏
I actually started implementing such a feature on a local branch, but it did not went well and felt kind of wrong for this library. The focus of `quickie` is about an easy integration with the camera and therefore UI focused. Calling native filepicker and sending the file uri to the scanner would require this library to decouple the barcode scanner from CameraX (which is currently not the case).

The part of the code which handles the ML Kit barcode scanner is honestly pretty small. So I would actually advice you to just follow the documentation about scanning files: [Using a file URI](https://developers.google.com/ml-kit/vision/barcode-scanning/android#using-a-file-uri)

I am sorry but because of these reasons I will reject this feature request.😞
