### ISSUE TITLE
Adaptation for easy implementation in Jetpack Compose

### ISSUE THREAD

**Issue by jeluchu** [G00fY2/quickie#34]
I would like to know if it is possible to use the library with Jetpack Compose, or if you have any approach to facilitate the implementation, or to include an example using it with this new Android Kit, currently you have indicated:

`private val scanCustomCode = registerForActivityResult(ScanCustomCode(), ::showSnackbar)
`

For Jetpack Compose it would probably look like this:

```
val result = remember { mutableStateOf<QRResult?>(null) }
val launcher = rememberLauncherForActivityResult(ScanCustomCode()) {
    result.value = it
}
```

Thank you very much in advance for your work with this library

**Comment by G00fY2** [comment]
Hi @Jeluchu, thanks for contacting me. Maybe I find time to set up a compose sample project, to test and show the Jetpack Compose integration. Then I could also update the Readme.

But did you search for the Activity Result API usage in Jetpack Compose? Since my library uses this standard API there should be no difference to other implementations:
- https://stackoverflow.com/questions/64721218/jetpack-compose-launch-activityresultcontract-request-from-composable-function
- https://stackoverflow.com/questions/67177271/how-to-handle-activity-onactivityresult-with-jetpack-compose

**Comment by Jeluchu** [comment]
@G00fY2 
Actually I have already implemented your library in my Compose project and it is more or less as I have indicated, I comment it in case you want to include it in the Readme.

At the top inside the Composable I get the result of the activity like this: 
```
    val launcher = rememberLauncherForActivityResult(ScanCustomCode()) { qrResult ->

        val text = when (qrResult) {
            is QRResult.QRSuccess -> qrResult.content.rawValue
            QRResult.QRUserCanceled -> "User canceled"
            QRResult.QRMissingPermission -> "Missing permission"
            is QRResult.QRError -> "${qrResult.exception.javaClass.simpleName}: ${qrResult.exception.localizedMessage}"
        }

      { ... } // Code for result

    }
```

And then I have this other piece of code that I call when I want to open the QR reader, in `ActivityResultLauncher<ScannerConfig>` I pass it the launcher variable indicated in the code snippet above

```
    val qrReader: (ActivityResultLauncher<ScannerConfig>) -> Unit = { qrReaderActivityResult ->
        qrReaderActivityResult.launch(
            ScannerConfig.build {
                setBarcodeFormats(listOf(BarcodeFormat.FORMAT_QR_CODE))
                setOverlayStringRes(R.string.scannerQrshopper)
                setHapticSuccessFeedback(false)
                setShowTorchToggle(true)
                setUseFrontCamera(false)
            }
        )
    }
```

In compose, the way to get the results of the activities changes from what we were used to in the old XML activities, that's why `rememberLauncherForActivityResult` is now used.

**Comment by G00fY2** [comment]
Thanks for clarifying and sharing your solution. ❤️ 
As I said, I will also try to set up a Compose Sample project in the future and than link it in the Readme.

Do you think it makes sense to keep the ticket open?

**Comment by jeluchu** [comment]
You're welcome! Thanks to you for your work with this library, of course no problem, you can close it 😄
