### ISSUE TITLE
Crash on certain devices

### ISSUE THREAD

**Issue by mmacagno** [G00fY2/quickie#48]
Related to #21 (could not reopen that one)

I worked with the Android team to fix the internal issue related to this.
however, your library is using a previous version of the CameraX implementation.

Could you upgrade to 

androidx.camera:camera-*:1.2.0-alpha01?

thanks

**Comment by G00fY2** [comment]
Thanks for letting me know.

You should be able to explicitly define this dependency in your project. Gradle should then use the latest dependency version found.

I will stick to the latest stable versions, since these are recommended for general usage and could otherwise break stuff for people using this library.

**Comment by mmacagno** [comment]
Ok I will give it a shot.

Sent with fat fingrs. Excuse the typos.
________________________________
